#!/bin/ksh

#type='h0zm'
type='h0'

runname='b40.1955-2005.2deg.wset.avg456'

#rootpath='/data5/mmills/wa319/carma-soot'
#rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
#rootpath='/data/waccm'
rootpath='/data/ccsm4'

wadir=$rootpath'/'$runname'/'$type
#wadir=$rootpath'/'$runname'/atm/hist'
anndir=$rootpath'/'$runname'/'$type'.annual'
searchstr='cam2.'$type
addstr='annual'

year1=1955
year2=2005


# script to average and standard deviation of waccm h0 files

mkdir -p $anndir

year=$year1
while [[ $year -le $year2 ]];do

  if [[ year -lt 10 ]]
    then
      yearstr='000'$year
    elif [[ year -lt 100 ]]
    then
      yearstr='00'$year
    elif [[ year -lt 1000 ]]
    then
      yearstr='0'$year
    else
      yearstr=$year
    fi
  
  ncfiles=$wadir'/'$runname'.'$searchstr'.'$yearstr*'.nc'
  avgfile=$anndir'/'$runname'.'$searchstr'.'$yearstr'.'$addstr'.nc'

  # create annual mean
  echo averaging $ncfiles
  ncea $ncfiles $avgfile
  echo created $avgfile
   
  (( year+=1 ))
     
done

echo "Annual averaging complete.  Now run fixdate.ncl to fix the dates!"

export runname
export anndir
export year1
export year2
export searchstr
export addstr

ncl $CODE_PATH/scripts/ncl/fixdate.ncl
