#!/bin/ksh
# script to average and standard deviation of waccm h0 files

if  [ -n "$caseid" ] ; then
  runname=$caseid
  
  export machine=`hostname`

  if [ ! -n "$hnum" ] ; then
    hnum='h0'
  fi

  if [ ! -n "$addstr" ] ; then
    addstr='annual'  # i.e. 'DJF'
  fi

  if [ ! -n "$subdir" ] ; then
    subdir=''
  fi

  if [[ $machine =~ 'mirage' ]];then
    rootpath='/CESM/wawg/runs'
  fi

  if [[ $machine = 'modeling1' ]];then
    rootpath='/data4/mmills'
  fi

  if [[ $machine = 'cmip5' ]];then
    rootpath='/data/waccm'
  fi

  if [[ $OSTYPE = 'darwin' ]];then
    rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
  fi
  
  wadir=$rootpath'/'$runname'/'$subdir'/'$hnum'.'$addstr

  # calculate mean

  echo ncrcat -O $wadir'/'$runname'.cam.'$hnum'.'*'.'$addstr'.nc' $wadir'/'annual_tmp.nc
  ncrcat -O $wadir'/'$runname'.cam.'$hnum'.'*'.'$addstr'.nc' $wadir'/'annual_tmp.nc 
  avgfile=$wadir'/'$runname'.cam.'$hnum'.'$addstr'.nc'

  echo ncwa -O -a time $wadir'/'annual_tmp.nc $avgfile
  ncwa -O -a time $wadir'/'annual_tmp.nc $avgfile
  #echo created $avgfile

  # calculate standard deviation 

  ncbo -O --op_typ=sub $wadir'/'annual_tmp.nc $avgfile $wadir'/'tmp.nc

  sdfile=$wadir'/'$runname'.cam.'$hnum'.'$addstr'_sd.nc'
  echo ncra -O -y rmssdn $wadir'/'tmp.nc $sdfile
  ncra -O -y rmssdn $wadir'/'tmp.nc $sdfile 
  #echo created $sdfile

  rm -f $wadir'/'tmp.nc
  rm -f $wadir'/'annual_tmp.nc
  
else
  echo "environment variable caseid is not set"
fi


