#!/bin/ksh

export machine=`hostname`

if [ ! -n "$rootpath" ] ; then

  if [[ $machine =~ 'yslogin' ]];then
#      rootpath='/glade/p/cesm/wawg/mmills/run'
    rootpath='/glade/scratch/mmills/archive'
  fi

  if [[ $machine = 'modeling1' ]];then
    rootpath='/data4/mmills'
  fi

  if [[ $machine = 'cmip5' ]];then
    rootpath='/data/waccm'
  #  rootpath='/data/ccsm4'
  fi

  if [[ $OSTYPE = 'darwin' ]];then
    rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
  fi

fi
echo "rootpath = $rootpath"

#if [ ! -n "$caseid" ] ; then
#  echo "caseid is not set: $caseid, i.e.:"
#  echo " export caseid=bc5tgIP"
#  if  ! -n $ensname ] ; then
#    echo " ensname not set; exiting: $ensname"
#    exit
#  fi
#  if  ! -n "$avgname" ] ; then
#    echo " avgname not set; exiting."
#    exit
#  fi
#fi

ensname=$ensemble'.00[123]'
echo "ensname = $ensname"
avgname=$ensemble'.avg'
echo "avgname = $avgname"
echo "hnum = $hnum"

if [ $caseid = 'bc5tgIP' ] ; then
  ensname='b40.rcp4_5.2deg.wcm.carma.bc5tgIP.00[367]'
  avgname='b40.rcp4_5.2deg.wcm.carma.bc5tgIP.avg'
  if [ ! -n "$year1" ] ; then
    year1=2013
  fi
  if [ ! -n "$year2" ] ; then
    year2=2022
  fi
fi

if [ $caseid = 'bc0tg' ] ; then
  ensname='b40.rcp4_5.2deg.wcm.carma.bc0tg.00[678]'
  avgname='b40.rcp4_5.2deg.wcm.carma.bc0tg.avg678'
  if [ ! -n "$year1" ] ; then
    year1=2013
  fi
  if [ ! -n "$year2" ] ; then
    year2=2022
  fi
fi

if [ ! -n "$year1" ] ; then
  year1=1991
fi
if [ ! -n "$year2" ] ; then
  year2=1992
fi
echo month1 $month1
if [ ! -n "$month1" ] ; then
  month1=1
fi
echo month1 $month1

#hno3_rename='b40.rcp2_6.2deg.wcm.002'
#ensname2='b40.rcp2_6.2deg.wcm.00[34]'
#outpath='/data/ccsm4'
outpath=$rootpath

#ensname='b40.rcp4_5.2deg.wcm.00[123]'
##ensname2='br04.20th.track1.2deg.wcm.pd.00[12]'
#avgname='b40.rcp4_5.2deg.wcm.avg'

if [ ! -n "$hnum" ] ; then
  hnum='h0'
fi

wadir=$rootpath'/'$ensname'/atm/proc/'$hnum
#wadir2=$rootpath'/'$ensname2'/'$hnum
avgdir=$outpath'/'$avgname'/atm/proc/'$hnum
searchstr='cam.'$hnum


# script to average and standard deviation of waccm h0 files

mkdir -p $avgdir

year=$year1
month=$month1
echo month $month

while [[ $year -le $year2 ]];do

  if [[ year -lt 10 ]]
    then
      yearstr='000'$year
    elif [[ year -lt 100 ]]
    then
      yearstr='00'$year
    elif [[ year -lt 1000 ]]
    then
      yearstr='0'$year
    else
      yearstr=$year
    fi
      
  while [[ $month -le 12 ]];do
  
    if [[ month -lt 10 ]]
      then
        monthstr='0'$month
      else
        monthstr=$month
      fi
      
    ncfiles=$wadir'/'$ensname'.'$searchstr'.'$yearstr'-'$monthstr'.nc'
#    ncfiles_rename=$wadir'/'$hno3_rename'.'$searchstr'.'$yearstr'-'$monthstr'.nc'
#    ncfiles_tmp=$wadir'/'$ensname'.'$searchstr'.'$yearstr'-'$monthstr'_tmp.nc'
#    ncfiles2=$wadir2'/'$ensname2'.'$searchstr'.'$yearstr'-'$monthstr'.nc'
    avgfile=$avgdir'/'$avgname'.'$searchstr'.'$yearstr'-'$monthstr'.nc'

    # "delete" missing variable to temporary file
#    echo ncks -x -v LCLOUD,LINOZ_DO3,LINOZ_DO3_PSC,LINOZ_O3CLIM,LINOZ_O3COL,LINOZ_SSO3,LINOZ_SZA,NDROPCOL,NDROPMIX,NDROPSNK,NDROPSRC,WTKE $ncfiles $ncfiles_tmp
#    ncks -O -x -v LCLOUD,LINOZ_DO3,LINOZ_DO3_PSC,LINOZ_O3CLIM,LINOZ_O3COL,LINOZ_SSO3,LINOZ_SZA,NDROPCOL,NDROPMIX,NDROPSNK,NDROPSRC,WTKE $ncfiles $ncfiles_tmp

     # "rename" condensed-phase HNO3 variables to new names
#    echo ncrename -v .HNO3_CD1,HNO3_STS -v .HNO3_CD3,HNO3_NAT $ncfiles_rename
#    ncrename -O -v .HNO3_CD1,HNO3_STS -v .HNO3_CD3,HNO3_NAT $ncfiles_rename

    # "delete" missing variable to temporary file
#    echo ncks -x -v NO2_CLXF,NO2_XFRC,ODV_H2SO4M,ODV_SSLTA,ODV_SSLTC,ODV_bcar1,ODV_bcar2,ODV_dust1,ODV_dust2,ODV_dust3,ODV_dust4,ODV_ocar1,ODV_ocar2,ODV_sulf $ncfiles $ncfiles_tmp
#    ncks -O -x -v NO2_CLXF,NO2_XFRC,ODV_H2SO4M,ODV_SSLTA,ODV_SSLTC,ODV_bcar1,ODV_bcar2,ODV_dust1,ODV_dust2,ODV_dust3,ODV_dust4,ODV_ocar1,ODV_ocar2,ODV_sulf $ncfiles $ncfiles_tmp

   # create ensemble mean
    echo ncea $ncfiles $avgfile
    ncea -O $ncfiles $avgfile

#    echo ncea $ncfiles_tmp $ncfiles2 $avgfile
#    ncea -O $ncfiles_tmp $ncfiles2 $avgfile

    # delete temporary file
#    echo rm $ncfiles_tmp
#    rm $ncfiles_tmp
    
    (( month+=1 ))
  
  done
   
  (( year+=1 ))
  month=1
     
done

