#!/bin/ksh

### reads zonal means in h0zm, h3zm and creates global means from all available years
#
# Define environment variables, i.e.:
#   export caseid=b40.rcp4_5.2deg.wcm.carma.bc5tgIP.avg
# Optional history tape (default h0):
#   export hnum=h3

echo " "
echo globavg

if  [ -n "$caseid" ] ; then

  export machine=`hostname`

  if [ ! -n "$rootpath" ] ; then

    if [[ $machine =~ 'yslogin' || $machine =~ 'geyser' || $machine =~ 'caldera' ]];then
#      rootpath='/glade/p/cesm/wawg/waccm'
      rootpath='/glade/scratch/mmills/archive'
    fi

#    if [[ $machine =~ 'geyser' ]];then
#      rootpath='/glade/p/cesm/wawg/mmills/run'
#    fi

#    if [[ $machine =~ 'caldera' ]];then
#      rootpath='/glade/p/cesm/wawg/mmills/run'
#    fi

    if [[ $machine =~ 'mirage' ]];then
      rootpath='/CESM/wawg/runs'
    fi

    if [[ $machine = 'modeling1' ]];then
      rootpath='/data4/mmills'
    fi

    if [[ $machine =~ 'lfe' ]];then
      rootpath='/lou/s2m/mjmills2/csm'
    fi

    if [[ $machine =~ 'pfe' ]];then
      rootpath='/nobackupp8/mjmills2/archive'
    fi

    if [[ $machine = 'cmip5' ]];then
      rootpath='/data/waccm'
    #  rootpath='/data/ccsm4'
    fi

    if [[ $OSTYPE = 'darwin' ]];then
      rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
    fi
    
  fi

  if [ ! -n "$runname" ] ; then
    runname=''
  fi

  if [ ! -n "$hnum" ] ; then
    hnum='h0'
  fi

  if [ ! -n "$htype" ] ; then
    htype=''
  fi

  zmdir=$rootpath'/'$caseid'/'$runname'/atm/proc/'$hnum'zm'$htype
  gmdir=$rootpath'/'$caseid'/'$runname'/atm/proc/'$hnum'gm'$htype
#  tmdir=$rootpath'/'$caseid'/'$runname'/atm/proc/'$hnum'tm'$htype
  tmdir=$rootpath'/'$caseid'/'$runname'/atm/proc/'$hnum'gm'$htype

  if [[ $machine = 'lou' ]];then
    rootpath=$HOME'/csm'
    zmdir=$rootpath'/'$caseid'/atm/'$hnum'zm'
    gmdir=$rootpath'/'$caseid'/atm/'$hnum'gm'
  fi

  mkdir -p $gmdir
  mkdir -p $tmdir

#==========================================================================

  avgfile=$gmdir'/'$caseid'.cam.'$hnum'.NHavg.nc'
  echo "mkdir $gmdir/tmpdir"
  mkdir $gmdir'/tmpdir'
  tmpfile=$gmdir'/tmpdir/zmtmp.nc'
  starttime=0
  
  if [[ -e $avgfile ]]; then
    lastdate=`ncks -C -v date $avgfile | tail -2 | head -1 | cut -d= -f3`
    echo "lastdate=$lastdate"
    lasttime=`ncks -C -v date $avgfile | tail -2 | head -1 | cut -d[ -f2 | cut -d] -f1`
    echo "lasttime=$lasttime"
    ((starttime=lasttime+1))
    echo "starttime=$starttime"
    startyear=`echo $lastdate|cut -c1-4`
    startmonth=`echo $lastdate|cut -c5-6`
    startdate=$startyear'-'$startmonth
    echo "startdate=$startdate"    
    avgfile2=$gmdir'/tmpdir/'$caseid'.cam.'$hnum'.tempavg.nc'
  fi

  if [[ ! -e $tmpfile ]];then
    echo " "
    echo "avgfile= $avgfile"
    ncfiles=$zmdir'/*.cam'*'.'$hnum'zm.*.nc'
    echo " "
    echo "ncrcat -O -d time,$starttime, $ncfiles $tmpfile"
    ncrcat -O -d time,$starttime, $ncfiles $tmpfile
  fi
  
  avgfile=$gmdir'/'$caseid'.cam.'$hnum'.globavg.nc'
  echo " "
  echo "avgfile= $avgfile"
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -I -a lat -w gw -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -I -a lat -w gw -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  avgfile=$tmdir'/'$caseid'.cam.'$hnum'.tropicsavg.nc'
  echo " "
  echo "avgfile= $avgfile"
    
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-23.4378,23.4378 -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -O -I -a lat -w gw -d lat,-23.4378,23.4378 -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-23.4378,23.4378 -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -d lat,-23.4378,23.4378 -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  avgfile=$tmdir'/'$caseid'.cam.'$hnum'.0-20N.nc'
  echo " "
  echo "avgfile= $avgfile"
    
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,0.0,20.0 -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -O -I -a lat -w gw -d lat,0.0,20.0 -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,0.0,20.0 -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -d lat,0.0,20.0 -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  avgfile=$tmdir'/'$caseid'.cam.'$hnum'.10N-10S.nc'
  echo " "
  echo "avgfile= $avgfile"
    
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-10.0,10.0 -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -O -I -a lat -w gw -d lat,-10.0,10.0 -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-10.0,10.0 -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -d lat,-10.0,10.0 -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  avgfile=$gmdir'/'$caseid'.cam.'$hnum'.NHavg.nc'
  echo " "
  echo "avgfile= $avgfile"
    
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,0.0,90.0 -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -O -I -a lat -w gw -d lat,0.0,90.0 -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,0.0,90.0 -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -d lat,0.0,90.0 -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  avgfile=$gmdir'/'$caseid'.cam.'$hnum'.SHavg.nc'
  echo " "
  echo "avgfile= $avgfile"
    
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-90.0,0.0 -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -O -I -a lat -w gw -d lat,-90.0,0.0 -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-90.0,0.0 -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -d lat,-90.0,0.0 -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  avgfile=$gmdir'/'$caseid'.cam.'$hnum'.NETavg.nc'
  echo " "
  echo "avgfile= $avgfile"
    
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,23.4378,90.0 -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -O -I -a lat -w gw -d lat,23.4378,90.0 -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,23.4378,90.0 -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -d lat,23.4378,90.0 -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  avgfile=$gmdir'/'$caseid'.cam.'$hnum'.SETavg.nc'
  echo " "
  echo "avgfile= $avgfile"
    
  if [[ ! -e $avgfile ]];then
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-90.0,-23.4378 -x -v nlon,wnummax $tmpfile $avgfile"
    ncwa -O -I -a lat -w gw -d lat,-90.0,-23.4378 -x -v nlon,wnummax $tmpfile $avgfile
  else
    echo " "
    echo "ncwa -O -I -a lat -w gw -d lat,-90.0,-23.4378 -x -v nlon,wnummax $tmpfile $avgfile2"
    ncwa -O -I -a lat -w gw -d lat,-90.0,-23.4378 -x -v nlon,wnummax $tmpfile $avgfile2
    echo "ncrcat -O $avgfile $avgfile2 $avgfile"
    ncrcat -O $avgfile $avgfile2 $avgfile
  fi
    
#==========================================================================

  echo " "
  echo "rm -rf $gmdir/tmpdir"
  rm -rf $gmdir/tmpdir
else
  echo "caseid is not set, i.e.:"
  echo " setenv caseid b40.rcp4_5.2deg.wcm.carma.bc5tgIP.avg"
fi


