#!/bin/ksh

### reads zonal means in h0zm, h3zm and creates global means from all available years
#
# Define environment variables, i.e.:
#   export caseid=b40.rcp4_5.2deg.wcm.carma.bc5tgIP.avg
# Optional history tape (default h0):
#   export hnum=h3

echo globavg

if  [ -n "$caseid" ] ; then

  export machine=`hostname`

  if [[ $machine = 'modeling1' ]];then
    rootpath='/data4/mmills'
  fi

  if [[ $machine = 'cmip5' ]];then
    rootpath='/data/waccm'
  #  rootpath='/data/ccsm4'
  fi

  if [[ $OSTYPE = 'darwin' ]];then
    rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
  fi

  if [ ! -n "$hnum" ] ; then
    hnum='h0'
  fi

  zmdir=$rootpath'/'$caseid'/'$hnum'zm'
  gmdir=$rootpath'/'$caseid'/'$hnum'gm'

  if [[ $machine = 'lou' ]];then
    rootpath=$HOME'/csm'
    zmdir=$rootpath'/'$caseid'/atm/'$hnum'zm'
    gmdir=$rootpath'/'$caseid'/atm/'$hnum'gm'
  fi

  mkdir -p $gmdir

  avgfile=$gmdir'/'$caseid'.cam2.'$hnum'.globavg.nc'
  tmpfile=$gmdir'/zmtmp.nc'

  echo $avgfile
  ncfiles=$zmdir'/'$caseid'.cam2.'$hnum'zm.*.nc'
  echo "ncrcat -O $ncfiles $tmpfile"
  ncrcat -O $ncfiles $tmpfile
    
  echo "ncwa -O -I -a lat -w gw -x -v nlon,wnummax $tmpfile $avgfile"
  ncwa -O -I -a lat -w gw -x -v nlon,wnummax $tmpfile $avgfile
    
  echo "rm $tmpfile"
  rm $tmpfile
else
  echo "caseid is not set, i.e.:"
  echo " setenv caseid b40.rcp4_5.2deg.wcm.carma.bc5tgIP.avg"
fi


