#!/bin/ksh

export machine=`hostname`

if [[ $machine = 'modeling1' ]];then
  rootpath='/data4/mmills'
fi

if [[ $machine = 'cmip5' ]];then
  rootpath='/data/waccm'
#  rootpath='/data/ccsm4'
fi

if [[ $OSTYPE = 'darwin' ]];then
  rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
fi

#maxtimes=113

caseid='b40.rcp4_5.2deg.wcm.carma.bc0tg.00[678]'
infiles=$rootpath'/'$caseid'/h0gm/'$caseid'.cam2.h0.globavg.nc'

outid='b40.rcp4_5.2deg.wcm.carma.bc0tg.avg678'
outpath=$rootpath'/'$outid'/h0gm'
outfile=$outpath'/'$outid'.cam2.h0.globavg.nc'

mkdir -p $outpath


#echo 'ncea -O -d time,0,'$maxtimes' '$infiles' '$outfile
#ncea -O -d time,0,$maxtimes $infiles $outfile
echo 'ncea -O '$infiles' '$outfile
ncea -O $infiles $outfile
