#!/bin/ksh

export machine=`hostname`

if [[ $machine = 'modeling1' ]];then
  rootpath='/data4/mmills'
#  rootpath='/data5/mmills/wa319/carma-soot'
fi

if [[ $machine = 'cmip5' ]];then
  rootpath='/data/waccm'
#  rootpath='/data/ccsm4'
fi

if [[ $OSTYPE = 'darwin' ]];then
  rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
fi

caseid1='b40.rcp4_5.2deg.wcm.carma.bc5tgIP.003'
caseid2='b40.rcp4_5.2deg.wcm.carma.bc5tgIP.006'
caseid3='b40.rcp4_5.2deg.wcm.carma.bc5tgIP.007'
ensemble='b40.rcp4_5.2deg.wcm.carma.bc5tgIP.avg'

#caseid1='b40.rcp4_5.2deg.wcm.carma.bc0tg.001'
#caseid2='b40.rcp4_5.2deg.wcm.carma.bc0tg.002'
#caseid3='b40.rcp4_5.2deg.wcm.carma.bc0tg.003'
#ensemble='b40.rcp4_5.2deg.wcm.carma.bc0tg.avg'

hnum='h3'

htype=''

wadir=$rootpath'/'$caseid1'/'$hnum$htype
ensdir=$rootpath'/'$ensemble'/'$hnum$htype
mkdir -p $ensdir

for a in `ls -1 $wadir/*$hnum.*.nc`; do
  file1=$a
  ls -sh $file1
  file2=`echo $file1 | sed 's/'$caseid1'/'$caseid2'/g'`
  file3=`echo $file1 | sed 's/'$caseid1'/'$caseid3'/g'`
  fileavg=`echo $file1 | sed 's/'$caseid1'/'$ensemble'/g'`
  if [[ -e $file2 ]];then
    ls -sh $file2
    if [[ -e $file3 ]];then
      ls -sh $file3
      echo ncea -O -v date,FSDS,PRECC,PRECL,TS,TSMX,TSMN $file1 $file2 $file3 $fileavg
      ncea -O -v date,FSDS,PRECC,PRECL,TS,TSMX,TSMN $file1 $file2 $file3 $fileavg
    else
      echo FATAL: missing file $file3
      exit
    fi
  else
    echo FATAL: missing file $file2
    exit
  fi

done
