#!/bin/ksh

###.......creates monthly means from all available years.......

#echo zmavg

if  [ -n "$caseid" ] ; then
  rootpath='/glade/scratch/mmills/archive/'
  
  if [[ $OSTYPE = 'darwin' ]];then
    rootpath='/Volumes/Data/Models/cesm/runs/cesm1_0/'
  fi

#  hnum='h0zm'
#  wadir=$rootpath'/'$caseid'/atm/proc/h0zm'
#  outdir=$rootpath'/'$caseid'/atm/proc/h0zm.monthavg'

  hnum='h0'  
  wadir=$rootpath'/'$caseid'/h0'
  outdir=$rootpath'/'$caseid'/h0.monthavg'
  
  echo "mkdir -p $outdir"
  mkdir -p $outdir

  set -A months 01 02 03 04 05 06 07 08 09 10 11 12

  echo ${months[*]}

  for month in ${months[*]}

  do

    echo "month: $month"

    # script to average and standard deviation of waccm h0 files

    ncfiles=$wadir'/'$caseid'.cam*.'$hnum'.*-'$month'.nc'

    avgfile=$outdir'/'$caseid'.cam.'$hnum'.'$month'.nc'

    echo $ncfiles
    echo $avgfile

#    echo "ncea -O -v lev,hyam,hybm,P0,ilev,hyai,hybi,date,lat,gw,CH4_CHML,OCS_CHML $ncfiles $avgfile"
#    ncea -O -v lev,hyam,hybm,P0,ilev,hyai,hybi,date,lat,gw,CH4_CHML,OCS_CHML $ncfiles $avgfile

    echo "ncea -O -v lev,hyam,hybm,P0,ilev,hyai,hybi,date,lat,gw,Z3 $ncfiles $avgfile"
    ncea -O -v lev,hyam,hybm,P0,ilev,hyai,hybi,date,lat,gw,Z3 $ncfiles $avgfile

  done

  echo "Successfully completed script monthavg."
else
  echo "caseid is not set"
fi
