#!/bin/sh

###.......creates DJF means for first and last 20-year periods of 20th Century run PSL time series 

rootpath=/data/ccsm4
let lim1=12*11-1
let lim2=1995-1850
let lim2=12*$lim2

filext1=cam2.h0.PSL.185001-200512
filext2=cam2.h0.PSL.185001-186012
filext3=cam2.h0.PSL.199501-200512

for idy in 005 006 007 008 009; do
  runname=b40.20th.track1.1deg.$idy
  wadir=$rootpath/$runname/proc
  
  file1=$wadir/$runname.$filext1
  file2=$wadir/$runname.$filext2
  file3=$wadir/$runname.$filext3
  echo $file1

  for idx in 01 02 12; do # DJF
    echo ncks -O -F -d time,${idx},${lim1},12 $file1.nc $file2.${idx}.nc
    ncks -O -F -d time,${idx},${lim1},12 $file1.nc $file2.${idx}.nc
    echo ncra -O $file2.${idx}.nc $file2.avg_${idx}.nc
    ncra -O $file2.${idx}.nc $file2.avg_${idx}.nc

    let lim3=$lim2+$idx
    echo ncks -O -F -d time,${lim3},,12 $file1.nc $file3.${idx}.nc
    ncks -O -F -d time,${lim3},,12 $file1.nc $file3.${idx}.nc
    echo ncra -O $file3.${idx}.nc $file3.avg_${idx}.nc
    ncra -O $file3.${idx}.nc $file3.avg_${idx}.nc
  done

  echo ncra -O $file2.avg_01.nc $file2.avg_02.nc $file2.avg_12.nc $file2.avg_DJF.nc
  ncra -O $file2.avg_01.nc $file2.avg_02.nc $file2.avg_12.nc $file2.avg_DJF.nc

  echo ncea -O $file3.avg_01.nc $file3.avg_02.nc $file3.avg_12.nc $file3.avg_DJF.nc
  ncra -O $file3.avg_01.nc $file3.avg_02.nc $file3.avg_12.nc $file3.avg_DJF.nc
done

echo ncea -O $rootpath/b40.20th.track1.1deg.00[5-9]/proc/*.$filext2.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext2.avg_DJF.nc
ncea -O $rootpath/b40.20th.track1.1deg.00[5-9]/proc/*.$filext2.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext2.avg_DJF.nc

echo -O ncea $rootpath/b40.20th.track1.1deg.00[5-9]/proc/*.$filext3.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext3.avg_DJF.nc
ncea -O $rootpath/b40.20th.track1.1deg.00[5-9]/proc/*.$filext3.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext3.avg_DJF.nc

echo ncdiff -O $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext3.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext2.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789.cam2.h0.PSL.diff.DJF.nc
ncdiff -O $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext3.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.$filext2.avg_DJF.nc \
     $rootpath/b40.20th.track1.1deg.avg56789/b40.20th.track1.1deg.avg56789.cam2.h0.PSL.diff.DJF.nc
     
echo "Successfully completed script tseriesSeasAvg."
