#!/bin/ksh

#rootpath='/data5/mmills/wa319/carma-soot'
#rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
#rootpath='/data5/mmills'
rootpath='/data/waccm'
#rootpath='/data/ccsm4'
caseid='b40.1850.2deg.wcm.qbosol.002'

hnum='h0'
#hnum='h3iso'

#htype='.annual'
htype=''

wadir=$rootpath'/'$caseid'/'$hnum$htype
outdir=$rootpath'/'$caseid'/'$hnum'zm'$htype

mkdir -p $outdir

for a in `ls -1 $wadir/*$hnum*.nc`; do
  oldfile=$a
  ls -sh $oldfile
  newfile=`echo $oldfile | sed 's/'$hnum'/'$hnum'zm/g' | sed 's/atm\/hist/h0zm/g'` # | sed 's/data2/data3/g' | sed 's/fischer/mmills/g'`

  if [[ ! -e $newfile ]];then
    echo "ncwa -alon -O "$oldfile" "$newfile
    ncwa -alon -O $oldfile $newfile
  fi
  
  ls -sh $newfile

done
