#!/bin/ksh
# Script creates zonal means from history files, skipping those previously created
# Define environment variables, i.e.:
#   setenv caseid b40.rcp4_5.2deg.wcm.carma.bc5tgIP.007
#   setenv runname run3
#   setenv hnum h0
#   setenv hnum h3iso
#   setenv htype '.annual'

if  [ -n "$caseid" ] ; then
  export machine=`hostname`
  
  if [ ! -n "$rootpath" ] ; then

    if [[ $machine =~ 'yslogin' ]];then
      rootpath='/glade/p/cesm/wawg/mmills/run'
    fi

    if [[ $machine =~ 'geyser' ]];then
      rootpath='/glade/p/cesm/wawg/mmills/run'
    fi

    if [[ $machine =~ 'caldera' ]];then
      rootpath='/glade/p/cesm/wawg/mmills/run'
    fi

    if [[ $machine =~ 'mirage' ]];then
      rootpath='/CESM/wawg/runs'
    fi

    if [[ $machine = 'modeling1' ]];then
      rootpath='/data4/mmills'
  #    rootpath='/data5/mmills/wa319/carma-soot'
    fi

    if [[ $machine = 'cmip5' ]];then
      if [[ $caseid =~ 'wcm' ]]; then
        rootpath='/data/waccm'
      else
        rootpath='/data/ccsm4'
      fi
    fi

    if [[ $OSTYPE = 'darwin' ]];then
      rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
    fi
    
  fi

  if [ ! -n "$runname" ] ; then
    runname=''
  fi

  if [ ! -n "$hnum" ] ; then
    hnum='h0'
  fi

  if [ ! -n "$htype" ] ; then
    htype=''
  fi

  if [ ! -n "$wadir" ] ; then
    wadir=$rootpath'/'$caseid'/'$runname'/atm/hist/'
  fi
  
  if [ ! -n "$outdir" ] ; then
    outdir=$rootpath'/'$caseid'/'$runname'/atm/proc/'$hnum'zm'$htype'/'
  fi
  
  echo "mkdir -p $outdir"
  mkdir -p $outdir
  
  cd $wadir
  pwd

  for a in `ls -1 *$hnum*.nc`; do
    oldfile=$a
    ls -sh $oldfile
    newfile=`echo $oldfile | sed 's/'$hnum'/'$hnum'zm/g'`

    if [[ ! -e $outdir$newfile ]];then
      echo "ncwa -alon -O "$oldfile" "$outdir"/"$newfile
      ncwa -alon -O $oldfile $outdir$newfile
    fi
  
    ls -sh $outdir$newfile

  done

else
  echo "caseid is not set"
fi
