#!/bin/ksh

export machine=`hostname`

if [[ $machine = 'modeling1' ]];then
  rootpath='/data4/mmills'
#  rootpath='/data5/mmills/wa319/carma-soot'
fi

if [[ $machine = 'cmip5' ]];then
  rootpath='/data/waccm'
#  rootpath='/data/ccsm4'
fi

if [[ $OSTYPE = 'darwin' ]];then
  rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
fi

#caseid='f40.2000.4deg.wcm.carma.sulf.004/run01'
caseid='b40.rcp4_5.2deg.wcm.carma.bc5tgIP.007'
#caseid='geo-0-bhn'

hnum='h3'
#hnum='h3iso'

#htype='.annual'
htype=''

wadir=$rootpath'/'$caseid'/'$hnum$htype
outdir=$rootpath'/'$caseid'/'$hnum'zm'$htype

mkdir -p $outdir

for a in `ls -1 $wadir/*$hnum*.nc`; do
  oldfile=$a
  ls -sh $oldfile
  newfile=`echo $oldfile | sed 's/'$hnum'/'$hnum'zm/g' | sed 's/atm\/hist/h0zm/g'` # | sed 's/data2/data3/g' | sed 's/fischer/mmills/g'`

  if [[ ! -e $newfile ]];then
    echo "ncwa -alon -O "$oldfile" "$newfile
    ncwa -alon -O $oldfile $newfile
  fi
  
  ls -sh $newfile

done
