#!/bin/ksh
# Script creates zonal means from history files, skipping those previously created
# Define environment variables, i.e.:
#   setenv caseid b40.rcp4_5.2deg.wcm.carma.bc5tgIP.007
#   setenv runname run3
#   setenv hnum h0
#   setenv hnum h3iso

if  [ -n "$caseid" ] ; then
  export machine=`hostname`
  
  if [ ! -n "$rootpath" ] ; then

    if [[ $machine =~ 'yslogin' ]];then
      rootpath='/glade/scratch/burakows/'
    fi

    if [[ $machine =~ 'geyser' ]];then
      rootpath='/glade/p/cesm/wawg/mmills/run'
    fi

    if [[ $machine =~ 'caldera' ]];then
      rootpath='/glade/p/cesm/wawg/mmills/run'
    fi

    if [[ $machine =~ 'mirage' ]];then
      rootpath='/CESM/wawg/runs'
    fi

    if [[ $machine = 'modeling1' ]];then
      rootpath='/data4/mmills'
  #    rootpath='/data5/mmills/wa319/carma-soot'
    fi

    if [[ $machine = 'cmip5' ]];then
      if [[ $caseid =~ 'wcm' ]]; then
        rootpath='/data/waccm'
      else
        rootpath='/data/ccsm4'
      fi
    fi

    if [[ $OSTYPE = 'darwin' ]];then
      rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
    fi
    
  fi

  if [ ! -n "$runname" ] ; then
    runname=''
  fi

  if [ ! -n "$hnum" ] ; then
    hnum='d03'
  fi

  if [ ! -n "$wadir" ] ; then
    wadir=$rootpath'/'$caseid'/'$runname'/run/'$hnum'/'
  fi
  
  if [ ! -n "$maxdir" ] ; then
    maxdir=$rootpath'/'$caseid'/'$runname'/run/'$hnum'_dmax/'
  fi
  
  if [ ! -n "$mindir" ] ; then
    mindir=$rootpath'/'$caseid'/'$runname'/run/'$hnum'_dmin/'
  fi
  
  echo "mkdir -p $maxdir"
  mkdir -p $maxdir
  
  echo "mkdir -p $mindir"
  mkdir -p $mindir
  
  cd $wadir
  pwd

  for a in `ls -1 *$hnum*`; do
    oldfile=$a
    ls -sh $oldfile
    maxfile=`echo $oldfile | sed 's/'$hnum'/'$hnum'_dmax/g'`
    minfile=`echo $oldfile | sed 's/'$hnum'/'$hnum'_dmin/g'`

    if [[ ! -e $maxdir$maxfile ]];then
      echo "ncra -a time -y max -v T2 -O "$oldfile" "$maxdir"/"$maxfile
      ncra -a time -y max -v T2 -O $oldfile $maxdir/$maxfile
    fi
  
    ls -sh $maxdir$maxfile

    if [[ ! -e $mindir$minfile ]];then
      echo "ncra -a time -y min -v T2 -O "$oldfile" "$mindir"/"$minfile
      ncra -a time -y min -v T2 -O $oldfile $mindir/$minfile
    fi
  
    ls -sh $mindir$minfile
    
  done

else
  echo "caseid is not set"
fi
