#!/bin/ksh

###.......creates monthly means from all available years.......

echo zmavg

#rootpath='/data5/mmills/wa319/carma-soot'
rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
runname='bccntl02'
#runname='bcrckt03'

wadir=$rootpath'/'$runname'/h0zm'
outdir=$rootpath'/'$runname'/h0zm.monavg'
mkdir -p $outdir

# script to average and standard deviation of waccm h0 files

count=1
while [[ $count -le 12 ]];do
   if  [[ $count -le 9 ]];then

      ncfiles=$wadir'/'$runname'.cam2.h0zm.*-0'$count'.nc'
      echo $ncfiles

      avgfile=$outdir'/'$runname'.cam2.h0zm.0'$count'.nc'
      sdfile=$outdir'/'$runname'.cam2.h0zmsd.0'$count'.nc'

   else

      ncfiles=$wadir'/'$runname'.cam2.h0zm.*-'$count'.nc'
      echo $ncfiles

      avgfile=$outdir'/'$runname'.cam2.h0zm.'$count'.nc'
      sdfile=$outdir'/'$runname'.cam2.h0zmsd.'$count'.nc'

   fi

   echo '-----------------'$count
   echo $avgfile
   echo $sdfile

   echo "ncrcat -O $ncfiles zmtmp.nc"
   ncrcat -O $ncfiles zmtmp.nc
   echo "ncwa -O -I -a time zmtmp.nc $avgfile"
   ncwa -O -I -a time zmtmp.nc $avgfile 
   echo "ncbo -O -D 2 --op_typ=sub zmtmp.nc $avgfile tmp.nc"
   ncbo -O -D 2 --op_typ=sub zmtmp.nc $avgfile tmp.nc
   echo "ncra -O -y rmssdn tmp.nc $sdfile"
   ncra -O -y rmssdn tmp.nc $sdfile
   rm zmtmp.nc
   rm tmp.nc

   (( count += 1 ))

done
