#!/bin/ksh

#runname='vgcontrol02'
#runname='b40.20th.track1.2deg.wcm.007'
#runname='b40.1850.track1.2deg.wcm.007'
#runname='b40.20th.2deg.wset.001'
#runname='b40.1955-2005.2deg.wcm.002'
#runname='bcrckt03'
runname='bccntl02'

#rootpath='/data5/mmills/wa319/carma-soot'
rootpath='/Volumes/Data/Models/waccm/run/carma-soot'

wadir=$rootpath'/'$runname'/h0zm'
anndir=$rootpath'/'$runname'/h0zm.annual'
searchstr='cam2.h0zm'
#wadir='/data3/mmills/'$runname'/h0'
#anndir='/data3/mmills/'$runname'/h0.annual'
#searchstr='cam2.h0'
addstr='annual'

year1=2035
year2=2066


# script to average and standard deviation of waccm h0 files

mkdir -p $anndir

year=$year1
while [[ $year -le $year2 ]];do

  if [[ year -lt 10 ]]
    then
      yearstr='000'$year
    elif [[ year -lt 100 ]]
    then
      yearstr='00'$year
    elif [[ year -lt 1000 ]]
    then
      yearstr='0'$year
    else
      yearstr=$year
    fi
  
  ncfiles=$wadir'/'$runname'.'$searchstr'.'$yearstr*'.nc'
  avgfile=$anndir'/'$runname'.'$searchstr'.'$yearstr'.'$addstr'.nc'

  # create annual mean
  echo averaging $ncfiles
  ncea $ncfiles $avgfile
  echo created $avgfile
   
  (( year+=1 ))
     
done

echo "Annual averaging complete.  Now run fixdate.ncl to fix the dates!"

export runname
export anndir
export year1
export year2
export searchstr
export addstr

ncl $CODE_PATH/ncl-scripts/fixdate.ncl
