#!/bin/ksh

#ensname='b40.1955-2005.2deg.wset.00[123]'
#avgname='b40.1955-2005.2deg.wset.avg'
#rootpath='/data/ccsm4'

ensname='b40.1955-2005.2deg.wcm.00[234]'
avgname='b40.1955-2005.2deg.wcm.avg'
rootpath='/data/waccm'

htype='h0zm'
wadir=$rootpath'/'$ensname'/'$htype
avgdir=$rootpath'/'$avgname'/'$htype
searchstr='cam2.'$htype

year1=1955
year2=2005


# script to average and standard deviation of waccm h0 files

mkdir -p $avgdir

year=$year1
while [[ $year -le $year2 ]];do

  if [[ year -lt 10 ]]
    then
      yearstr='000'$year
    elif [[ year -lt 100 ]]
    then
      yearstr='00'$year
    elif [[ year -lt 1000 ]]
    then
      yearstr='0'$year
    else
      yearstr=$year
    fi
    
  month=1
  
  while [[ $month -le 12 ]];do
  
    if [[ month -lt 10 ]]
      then
        monthstr='0'$month
      else
        monthstr=$month
      fi
      
    ncfiles=$wadir'/'$ensname'.'$searchstr'.'$yearstr'-'$monthstr'.nc'
    avgfile=$avgdir'/'$avgname'.'$searchstr'.'$yearstr'-'$monthstr'.nc'

    # create ensemble mean
    echo ncea $ncfiles $avgfile
    ncea $ncfiles $avgfile
    
    (( month+=1 ))
  
  done
   
  (( year+=1 ))
     
done

