#!/bin/ksh

###.......creates monthly means from all available years.......

  echo zmavg

#rootpath='/data5/mmills/wa319/carma-soot'
  rootpath='/Volumes/Data/Models/waccm/run/carma-soot'
  runname='bccntl02'
#  runname='bcrckt03'

# Dec, Jan, Feb
#  addstr='DJF'
# Jun, Jul, Aug
  addstr='JJA'

  wadir=$rootpath'/'$runname'/h0zm.'$addstr

# Dec, Jan, Feb
#  avgfile=$wadir'/'$runname'.cam2.h0zm.'$addstr'.15-45N.nc'
#  sdfile=$wadir'/'$runname'.cam2.h0zmsd.'$addstr'.15-45N.nc'
#  avgfile=$wadir'/'$runname'.cam2.h0zm.'$addstr'.15-30N.nc'
#  sdfile=$wadir'/'$runname'.cam2.h0zmsd.'$addstr'.15-30N.nc'

# Jun, Jul, Aug
#  avgfile=$wadir'/'$runname'.cam2.h0zm.'$addstr'.30-60S.nc'
#  sdfile=$wadir'/'$runname'.cam2.h0zmsd.'$addstr'.30-60S.nc'
  avgfile=$wadir'/'$runname'.cam2.h0zm.'$addstr'.60-75S.nc'
  sdfile=$wadir'/'$runname'.cam2.h0zmsd.'$addstr'.60-75S.nc'
  
  echo $avgfile
  echo $sdfile
  
  ncfiles=$wadir'/'$runname'.cam2.h0zm.20*.'$addstr'.nc'

  echo "ncrcat -O $ncfiles zmtmp.nc"
  ncrcat -O $ncfiles zmtmp.nc
  
# Dec, Jan, Feb
#  echo "ncwa -O -I -a lat -d lat,15.0,45.0 -w gw zmtmp.nc zmtmp2.nc"
#  ncwa -O -I -a lat -d lat,15.0,45.0 -w gw zmtmp.nc zmtmp2.nc
#  echo "ncwa -O -I -a lat -d lat,15.0,30.0 -w gw zmtmp.nc zmtmp2.nc"
#  ncwa -O -I -a lat -d lat,15.0,30.0 -w gw zmtmp.nc zmtmp2.nc
  
# Jun, Jul, Aug
#  echo "ncwa -O -I -a lat -d lat,-60.0,-30.0 -w gw zmtmp.nc zmtmp2.nc"
#  ncwa -O -I -a lat -d lat,-60.0,-30.0 -w gw zmtmp.nc zmtmp2.nc
  echo "ncwa -O -I -a lat -d lat,-75.0,-60.0 -w gw zmtmp.nc zmtmp2.nc"
  ncwa -O -I -a lat -d lat,-75.0,-60.0 -w gw zmtmp.nc zmtmp2.nc
  
  echo "ncwa -O -I -a time zmtmp2.nc $avgfile"
  ncwa -O -I -a time zmtmp2.nc $avgfile
   
  echo "ncbo -O -D 2 --op_typ=sub zmtmp2.nc $avgfile tmp.nc"
  ncbo -O -D 2 --op_typ=sub zmtmp2.nc $avgfile tmp.nc
  
  echo "ncra -O -y rmssdn tmp.nc $sdfile"
  ncra -O -y rmssdn tmp.nc $sdfile
  
  rm zmtmp.nc
  rm zmtmp2.nc
  rm tmp.nc

